### ISSUE TITLE
pascal case "error404" is converted to sentence case "Error404" instead of "Error 404"

### ISSUE THREAD

**Issue by khalyomede** [jawira/case-converter#85]
This one is a ltitle bit tricky because it seems on the internet all case converters are producing the same output, which bugs me. 

How is a **sentence** case algorithm not considering words ending with numbers 2 seperate entities, and "__toString" will trim the underscores, but still produce a single word (https://github.com/jawira/case-converter/issues/84)? Seems like there is something I do not get with the logic.

**Comment by jawira** [comment]
Hello, yes this is a bit tricky to understand.
The reason for this behavior is that since numbers cannot be converted to uppercase, Case Converter considers letters to be lowercase characters.

This is described in documentation, in "Known issues" section: <https://jawira.github.io/case-converter/known-issues.html> please read documentation for further details.

![image](https://github.com/user-attachments/assets/6c0060aa-5d2b-475a-bb91-719e55a7c6e7)

I will close this issue, but feel free to create new issues if you have more comments or need help.
